export const FETCHING_DATA = 'FETCHING_DATA';

export const ADD_PRODUCT    = 'ADD_PRODUCT';
export const SHOW_PRODUCT   = 'SHOW_PRODUCT';
export const SHOW_PRODUCT_ERROR = 'SHOW_PRODUCT_ERROR';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const EDIT_PRODUCT   = 'EDIT_PRODUCT';
export const DELETED_PRODUCT    = 'DELETED_PRODUCT';
export const DELETING_PRODUCT    = 'DELETING_PRODUCT';

export const LOADING_SINGLE            = 'LOADING_SINGLE';
export const SHOW_SINGLE_PRODUCT       = 'SHOW_SINGLE_PRODUCT';
export const SHOW_SINGLE_PRODUCT_ERROR = 'SHOW_SINGLE_PRODUCT_ERROR';
export const SHOW_PRODUCT_DETAIL       = 'SHOW_PRODUCT_DETAIL';
export const SHOW_PRODUCT_OWNER        = 'SHOW_PRODUCT_OWNER';
export const SHOW_PRODUCT_OWNER_ERROR  = 'SHOW_PRODUCT_OWNER_ERROR';
export const PRODUCT_OWNER_FETCHING    = 'PRODUCT_OWNER_FETCHING';
export const SHOW_PRODUCT_CATEGORY     = 'SHOW_PRODUCT_CATEGORY';
export const SHOW_PRODUCT_CATEGORY_ERROR = 'SHOW_PRODUCT_CATEGORY_ERROR';
export const CAN_YOU_LIKE     = 'CAN_YOU_LIKE';
export const CAN_YOU_LIKE_ERROR = 'CAN_YOU_LIKE_ERROR';

export const LOADING_DATA = 'LOADING_DATA';
export const SHOW_PRODUCT_REQUEST = 'SHOW_PRODUCT_REQUEST';

export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const LOGIN_FAIL     = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS  = 'REGISTER_SUCCESS';
export const REGISTER_FAIL     = 'REGISTER_FAIL';
export const REQUESTING        = 'REQUESTING';

export const SHOW_CATEGORY  = 'SHOW_CATEGORY';

export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR   = 'UPLOAD_ERROR';

export const ADDING_AUCTION   = 'ADDING_AUCTION';
export const ADDED_AUCTION_SUCCESS   = 'ADDED_AUCTION_SUCCESS';

export const ADDING_EXCHANGE   = 'ADDING_EXCHANGE';
export const ADDED_EXCHANGE_SUCCESS   = 'ADDED_EXCHANGE_SUCCESS';
export const ADDED_EXCHANGE_ERROR     = 'ADDED_EXCHANGE_ERROR';

export const ADD_PROGRESSING   = 'ADD_PROGRESSING';
export const ADD_PROGRESS      = 'ADD_PROGRESS';
export const ADD_PROGRESS_ERROR= 'ADD_PROGRESS_ERROR';

export const UPLOADING             = 'UPLOADING';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR   = 'UPLOAD_AVATAR_ERROR';

export const UPLOADING_PASS      = 'UPLOADING_PASS';
export const UPLOAD_PASS_SUCCESS = 'UPLOAD_PASS_SUCCESS';
export const UPLOAD_PASS_ERROR   = 'UPLOAD_PASS_ERROR';


export const UPDATING_USER       = 'UPDATING_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR   = 'UPDATE_USER_ERROR';

export const LOADING_TRANS_USER    = 'LOADING_TRANS_USER';
export const TRANS_OF_USER_SUCCESS = 'TRANS_OF_USER_SUCCESS';
export const TRANS_OF_USER_ERROR   = 'TRANS_OF_USER_ERROR';

export const LOADING_TRANS_ALL = 'LOADING_TRANS_ALL';
export const TRANS_ALL_SUCCESS = 'TRANS_ALL_SUCCESS';
export const TRANS_ALL_ERROR   = 'TRANS_ALL_ERROR';

export const LOADING_STATUS = 'LOADING_STATUS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_ERROR   = 'STATUS_ERROR';

export const LOADING_All_USER = 'LOADING_All_USER';
export const LOAD_ALL_USER_SUCCESS = 'LOAD_ALL_USER_SUCCESS';
export const LOAD_ALL_USER_ERROR   = 'LOAD_ALL_USER_ERROR';

export const LOADING_LIST_CHAT = 'LOADING_LIST_CHAT';
export const LOAD_LIST_CHAT_SUCCESS = 'LOAD_LIST_CHAT_SUCCESS';
export const LOAD_LIST_CHAT_ERROR   = 'LOAD_LIST_CHAT_ERROR';

export const LOADING_CHAT_WITH = 'LOADING_CHAT_WITH';
export const LOAD_CHAT_WITH_SUCCESS = 'LOAD_CHAT_WITH_SUCCESS';
export const LOAD_CHAT_WITH_ERROR   = 'LOAD_CHAT_WITH_ERROR';

export const LOADING_SHOW_MESSAGE = 'LOADING_SHOW_MESSAGE';
export const SHOW_MESSAGE_SUCCESS = 'SHOW_MESSAGE_SUCCESS';
export const SHOW_MESSAGE_ERROR   = 'SHOW_MESSAGE_ERROR';

export const TOGGLE_CHAT_BOX   = 'TOGGLE_CHAT_BOX';

export const LOADING_SHOW_CHATLIST = 'LOADING_SHOW_CHATLIST';
export const SHOW_CHATLIST_SUCCESS = 'SHOW_CHATLIST_SUCCESS';
export const SHOW_CHATLIST_ERROR   = 'SHOW_CHATLIST_ERROR';

export const LOADING_SEND_MESSAGE = 'LOADING_SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR   = 'SEND_MESSAGE_ERROR';

export const LOADING_AUCTION = 'LOADING_AUCTION';
export const AUCTION_SUCCESS = 'AUCTION_SUCCESS';
export const AUCTION_ERROR   = 'AUCTION_ERROR';

export const LOADING_REMOVE_AUCTION = 'LOADING_REMOVE_AUCTION';
export const REMOVE_AUCTION_SUCCESS = 'REMOVE_AUCTION_SUCCESS';
export const REMOVE_AUCTION_ERROR   = 'REMOVE_AUCTION_ERROR';

export const LOADING_CHANGE = 'LOADING_CHANGE';
export const CHANGE_SUCCESS = 'CHANGE_SUCCESS';
export const CHANGE_ERROR   = 'CHANGE_ERROR';

export const LOADING_REMOVE_CHANGE = 'LOADING_REMOVE_CHANGE';
export const REMOVE_CHANGE_SUCCESS = 'REMOVE_CHANGE_SUCCESS';
export const REMOVE_CHANGE_ERROR   = 'REMOVE_CHANGE_ERROR';
